[env]
ENV_DIR = {source="${CARGO_MAKE_PROFILE}", default_value = "debug", mapping = {release = "release"}}
CARGO_TARGET_DIR = {value = "target", condition = {env_not_set = ["CARGO_TARGET_DIR"]}}
CARGO_WASM_PATH = "${CARGO_TARGET_DIR}/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm"
TARGET_DIR = "target"
CARGO_MANIFEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"
CARGO_RELEASE_ARGS = "--release"

[env.release]
CARGO_WASM_PATH = "${CARGO_TARGET_DIR}/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm"
CARGO_RELEASE_ARGS = "--release"

[tasks.show-env]
command = "env"

[tasks.basic-http-server]
install_crate = {crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help"}

[tasks.wasm-bindgen-cli]
install_crate = {crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help"}

[tasks.cargo-build-web]
args = ["build", "--target", "wasm32-unknown-unknown", "--features", "web", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.cargo-release-web]
args = ["build", "--target", "wasm32-unknown-unknown", "--features", "web", "--release"]
command = "cargo"

[tasks.build-web]
args = ["--out-dir", "${TARGET_DIR}", "--out-name", "wasm", "--target", "web", "--no-typescript", "${CARGO_WASM_PATH}"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web", "wasm-bindgen-cli"]

[tasks.prepare-release-web]
dependencies = ["cargo-release-web", "wasm-bindgen-cli", "copy-wasm-to-build-dir", "copy-index-to-build-dir", "copy-assets-to-build-dir"]

[tasks.copy-wasm-to-build-dir]
args = ["target/wasm32-unknown-unknown/release/mini_jam_71.wasm", "mini_jam_71_web/target/"]
command = "cp"
dependencies = ["create-build-dir"]

[tasks.copy-assets-to-build-dir]
args = ["-r", "assets", "mini_jam_71_web"]
command = "cp"
dependencies = ["create-build-dir"]

[tasks.copy-index-to-build-dir]
args = ["index.html", "mini_jam_71_web/"]
command = "cp"
dependencies = ["create-build-dir"]

[tasks.create-build-dir]
args = ["-p", "mini_jam_71_web/target"]
command = "mkdir"

[tasks.release-web]
args = ["--out-dir", "mini_jam_71_web/target/", "--out-name", "wasm", "--target", "web", "--no-typescript", "mini_jam_71_web/target/mini_jam_71.wasm"]
command = "wasm-bindgen"
dependencies = ["prepare-release-web"]

[tasks.build-native]
args = ["build", "--features", "native", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.run]
command = "${CARGO_TARGET_DIR}/${ENV_DIR}/${CARGO_MAKE_BINARY_EXECUTABLE_NAME}"
dependencies = ["build-native"]

[tasks.serve]
command = "basic-http-server"
args = ["-x"]
dependencies = ["build-web", "basic-http-server"]

[tasks.test]
disabled = true
