pre-release-replacements = [
    {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"},
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
]
pre-release-commit-message=":rocket: version {{version}}"
post-release-commit-message=":construction: start next development iteration {{next_version}}"
tag-prefix="v"
tag-name="{{prefix}}{{version}}"
tag-message=":bookmark: {{version}}"
dev-version-ext="dev"
