name: release-flow

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# on: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-macOS:
    runs-on: macOS-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and release
        run: |
          cargo build --release --features native
          mkdir -p build/macos/Oicana.app/Contents/MacOS/assets
          cp -r assets/ build/macos/Oicana.app/Contents/MacOS/assets
          cp target/release/oicana build/macos/Oicana.app/Contents/MacOS/
          strip build/macos/Oicana.app/Contents/MacOS/oicana
          hdiutil create -fs HFS+ -volname "Oicana" -srcfolder build/macos oicana.dmg
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oicana.dmg
          asset_name: oicana_macOS_${{ steps.tag.outputs.tag }}.dmg
          tag: ${{ github.ref }}
          overwrite: true

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Build and release
        run: |
          cargo build --release --features native
          strip target/release/oicana
      - name: Prepare assets
        run: |
          mkdir target/release/assets && cp -r assets target/release/assets
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/assets/ target/release/oicana
          dest: oicana_linux.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oicana_linux.zip
          asset_name: oicana_linux_${{ steps.tag.outputs.tag }}.zip
          tag: ${{ github.ref }}
          overwrite: true

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and release
        run: |
          cargo build --release --features native
      - name: Prepare assets
        run: |
          mkdir target/release/assets && cp -r assets target/release/assets
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/assets/ target/release/oicana.exe
          dest: oicana_windows.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oicana_windows.zip
          asset_name: oicana_windows_${{ steps.tag.outputs.tag }}.zip
          tag: ${{ github.ref }}
          overwrite: true

  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Install cargo-make
        run: |
          cargo install cargo-make
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build Release
        run: |
          cargo make release-web
      - uses: papeloto/action-zip@v1
        with:
          files: oicana_web
          dest: oicana_web.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oicana_web.zip
          asset_name: oicana_web_${{ steps.tag.outputs.tag }}.zip
          tag: ${{ github.ref }}
          overwrite: true
